server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ticketbroker
    static_configs:
      - targets:
          - localhost
        labels:
          job: ticketbroker
          __path__: /var/log/app/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?P<message>.*)$'
      - labels:
          timestamp:
          level:
      - output:
          source: message

